node {
    stage('Build') {
        docker.image('maven:3.9.9-eclipse-temurin-21').inside {
            checkout scm
            sh 'mvn -B -DskipTests clean package'
        }
    }

    stage('Test') {
        docker.image('maven:3.9.9-eclipse-temurin-21').inside {
            sh 'mvn test'
            junit 'target/surefire-reports/*.xml'
        }
    }

    stage('Deliver') {
        sh 'chmod +x ./jenkins/scripts/deliver.sh'
        sh './jenkins/scripts/deliver.sh'
    }
}
